# Generated by Django 5.1.3 on 2026-04-23 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0002_initial'),
        ('modules', '0003_seed_modules'),
        ('nomenclature', '0002_initial'),
        ('organizations', '0002_initial'),
        ('purchases', '0003_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCostEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('egg_inherited', 'Инкуб. яйцо (унаслед.)'), ('feed', 'Комбикорм'), ('vet', 'Ветпрепараты'), ('labor', 'Зарплата'), ('utilities', 'Коммуналка'), ('depreciation', 'Амортизация'), ('transfer_in', 'Переход от другого модуля'), ('other', 'Прочее')], db_index=True, max_length=24)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Затрата по партии',
                'verbose_name_plural': 'Затраты по партии',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('accumulated_cost_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('state', models.CharField(choices=[('active', 'Активна'), ('in_transit', 'В пути'), ('completed', 'Завершена'), ('rejected', 'Отклонена'), ('review', 'На проверке')], db_index=True, default='active', max_length=16)),
                ('started_at', models.DateField()),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_batches', to='warehouses.productionblock')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches_current', to='modules.module')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='nomenclature.nomenclatureitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='organizations.organization')),
                ('origin_counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='counterparties.counterparty')),
                ('origin_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches_originated', to='modules.module')),
                ('origin_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originated_batches', to='purchases.purchaseorder')),
                ('parent_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_batches', to='batches.batch')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.unit')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'ordering': ['-started_at', 'doc_number'],
            },
        ),
        migrations.CreateModel(
            name='BatchChainStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_in', models.DecimalField(decimal_places=3, max_digits=18)),
                ('quantity_out', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('accumulated_cost_at_exit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_steps', to='batches.batch')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_chain_steps', to='warehouses.productionblock')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_chain_steps', to='modules.module')),
            ],
            options={
                'verbose_name': 'Шаг чейна партии',
                'verbose_name_plural': 'Шаги чейна партий',
                'ordering': ['batch', 'sequence'],
            },
        ),
    ]
