# Generated by Django 5.1.3 on 2026-04-23 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('modules', '0003_seed_modules'),
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchchainstep',
            name='transfer_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_as_target', to='transfers.intermoduletransfer'),
        ),
        migrations.AddField(
            model_name='batchchainstep',
            name='transfer_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_as_source', to='transfers.intermoduletransfer'),
        ),
        migrations.AddField(
            model_name='batchcostentry',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_entries', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='batchcostentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchcostentry',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_cost_entries', to='modules.module'),
        ),
        migrations.AddField(
            model_name='batchcostentry',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', 'state'], name='batches_bat_organiz_3b49de_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['current_module', 'state'], name='batches_bat_current_099dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['organization', '-started_at'], name='batches_bat_organiz_ecea99_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['parent_batch'], name='batches_bat_parent__a4c8f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('organization', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='batchchainstep',
            index=models.Index(fields=['batch', 'sequence'], name='batches_bat_batch_i_e7bf53_idx'),
        ),
        migrations.AddIndex(
            model_name='batchchainstep',
            index=models.Index(fields=['module'], name='batches_bat_module__20d65c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchchainstep',
            unique_together={('batch', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='batchcostentry',
            index=models.Index(fields=['batch', 'occurred_at'], name='batches_bat_batch_i_1466b5_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcostentry',
            index=models.Index(fields=['batch', 'category'], name='batches_bat_batch_i_b815b0_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcostentry',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='batches_bat_source__55bdec_idx'),
        ),
    ]
