# Generated by Django 5.1.3 on 2026-04-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='withdrawal_period_ends',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
