# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0002_initial'),
        ('nomenclature', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line_total_foreign', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('line_total_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='nomenclature.nomenclatureitem')),
            ],
            options={
                'verbose_name': 'Строка закупа',
                'verbose_name_plural': 'Строки закупа',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Проведён'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='draft', max_length=16)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('amount_foreign', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='counterparties.counterparty')),
            ],
            options={
                'verbose_name': 'Закуп',
                'verbose_name_plural': 'Закупы',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
