# Generated by Django 5.1.3 on 2026-04-23 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('counterparties', '0002_initial'),
        ('currency', '0001_initial'),
        ('modules', '0003_seed_modules'),
        ('organizations', '0002_initial'),
        ('purchases', '0003_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originating_purchases', to='batches.batch'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['batch'], name='purchases_p_batch_i_b52200_idx'),
        ),
    ]
