# Generated by Django 5.1.3 on 2026-04-23 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_withdrawal_period_ends'),
        ('counterparties', '0002_initial'),
        ('currency', '0001_initial'),
        ('modules', '0003_seed_modules'),
        ('organizations', '0002_initial'),
        ('purchases', '0004_purchaseorder_batch_and_more'),
        ('warehouses', '0003_alter_productionblock_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='paid_amount_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Частично оплачен'), ('paid', 'Оплачен'), ('overpaid', 'Переплата')], db_index=True, default='unpaid', max_length=16),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['payment_status'], name='purchases_p_payment_868427_idx'),
        ),
    ]
