# Generated by Django 5.1.3 on 2026-04-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchaseorder_exchange_rate_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='received_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Фактически принятое количество (частичная поставка).', max_digits=18),
        ),
    ]
