# Generated by Django 5.1.3 on 2026-05-04 06:25

import apps.purchases.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_business_logic_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.purchases.models._purchase_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'csv'])])),
                ('original_name', models.CharField(help_text='Имя файла как загружено пользователем (для скачивания).', max_length=255)),
                ('size_bytes', models.PositiveIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, help_text='Краткое описание: «договор поставки», «скан заявления», ...', max_length=255)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchases.purchaseorder')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приложение к закупу',
                'verbose_name_plural': 'Приложения к закупам',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase', '-created_at'], name='purchases_p_purchas_239ab0_idx')],
            },
        ),
    ]
