# Generated by Django 5.1.3 on 2026-05-06 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_seed_sales_module'),
        ('purchases', '0008_purchaseattachment'),
        ('warehouses', '0006_stockmovement_shrinkage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='kind',
            field=models.CharField(choices=[('regular', 'Обычный'), ('opening_balance', 'Стартовый долг (миграция)')], db_index=True, default='regular', help_text='Источник заказа. REGULAR — обычный закуп. OPENING_BALANCE — синтетический счёт миграции (без позиций / складов / прихода).', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Source module. NULL только для kind=opening_balance — у синтетического счёта модуля нет.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='modules.module'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Куда приход. NULL только для kind=opening_balance — у синтетического счёта склада нет.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='warehouses.warehouse'),
        ),
    ]
