# Generated by Django 5.1.3 on 2026-04-23 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('asset', 'Актив'), ('liability', 'Пассив'), ('equity', 'Капитал'), ('income', 'Доход'), ('expense', 'Затраты'), ('service', 'Служебный')], max_length=16)),
            ],
            options={
                'verbose_name': 'Счёт ГК',
                'verbose_name_plural': 'План счетов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GLSubaccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Субсчёт',
                'verbose_name_plural': 'Субсчета',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('entry_date', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=500)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_foreign', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводки',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
