# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('counterparties', '0002_initial'),
        ('modules', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glaccount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_accounts', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='glsubaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subaccounts', to='accounting.glaccount'),
        ),
        migrations.AddField(
            model_name='glsubaccount',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_subaccounts', to='modules.module'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='counterparties.counterparty'),
        ),
    ]
