# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('currency', '0001_initial'),
        ('modules', '0002_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit_subaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='accounting.glsubaccount'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit_subaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='accounting.glsubaccount'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='modules.module'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='glaccount',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='glsubaccount',
            index=models.Index(fields=['code'], name='accounting__code_398c39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='glsubaccount',
            unique_together={('account', 'code')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', '-entry_date'], name='accounting__organiz_abfc5c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='accounting__source__1c8e9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('organization', 'doc_number')},
        ),
    ]
