# Generated by Django 5.1.3 on 2026-04-23 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_initial'),
        ('batches', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('counterparties', '0002_initial'),
        ('currency', '0001_initial'),
        ('modules', '0003_seed_modules'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='batches.batch'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['batch'], name='accounting__batch_i_3f0332_idx'),
        ),
    ]
