# Generated by Django 5.1.3 on 2026-04-24 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_seed_opex_accounts'),
        ('modules', '0006_seed_sales_module'),
        ('organizations', '0003_organizationmembership_work_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход'), ('salary', 'Зарплата'), ('transfer', 'Перевод/прочее')], db_index=True, default='expense', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('default_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_articles', to='modules.module')),
                ('default_subaccount', models.ForeignKey(blank=True, help_text='Субсчёт ГК по умолчанию. При выборе этой статьи в OPEX-модалке субсчёт подставится автоматически.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_articles', to='accounting.glsubaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_articles', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.expensearticle')),
            ],
            options={
                'verbose_name': 'Статья расходов/доходов',
                'verbose_name_plural': 'Статьи расходов/доходов',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='expense_article',
            field=models.ForeignKey(blank=True, help_text='Аналитическая статья расходов/доходов поверх плана счетов. Заполняется автоматически из Payment.expense_article при post_payment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.expensearticle'),
        ),
        migrations.AddIndex(
            model_name='expensearticle',
            index=models.Index(fields=['organization', 'kind', 'is_active'], name='accounting__organiz_3adecf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensearticle',
            unique_together={('organization', 'code')},
        ),
    ]
