# Generated by Django 5.1.3 on 2026-04-30 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_seed_expense_articles'),
        ('organizations', '0004_rename_default_org_name'),
        ('payments', '0003_payment_expense_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAdvance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('issued_date', models.DateField(db_index=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(help_text='На что выдан подотчёт (например «закупка ГСМ для трактора»).', max_length=300)),
                ('amount_uzs', models.DecimalField(decimal_places=2, help_text='Сколько выдали наличными.', max_digits=18)),
                ('spent_amount_uzs', models.DecimalField(decimal_places=2, default=0, help_text='По чекам / отчёту — сколько потрачено.', max_digits=18)),
                ('returned_amount_uzs', models.DecimalField(decimal_places=2, default=0, help_text='Сколько вернули в кассу остатком (= amount − spent).', max_digits=18)),
                ('status', models.CharField(choices=[('issued', 'Выдано'), ('reported', 'Отчитался'), ('closed', 'Закрыто'), ('cancelled', 'Отменено')], db_index=True, default='issued', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('closing_journal_entry', models.OneToOneField(blank=True, help_text='Проводка списания на расходную статью при закрытии.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closes_advance', to='accounting.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_advances_created', to=settings.AUTH_USER_MODEL)),
                ('expense_article', models.ForeignKey(blank=True, help_text='Статья расходов, на которую списываются потраченные средства при закрытии. Если не указана — закрытие требует ручной правки JE.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_advances', to='accounting.expensearticle')),
                ('issued_payment', models.OneToOneField(blank=True, help_text='Платёж OUT, который выдал наличные сотруднику.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_issued_for', to='payments.payment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_advances', to='organizations.organization')),
                ('recipient', models.ForeignKey(help_text='Сотрудник, которому выдан подотчёт.', on_delete=django.db.models.deletion.PROTECT, related_name='cash_advances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подотчёт (выданная наличка)',
                'verbose_name_plural': 'Подотчёты',
                'ordering': ['-issued_date', '-doc_number'],
                'indexes': [models.Index(fields=['organization', 'status'], name='accounting__organiz_d7e736_idx'), models.Index(fields=['recipient', 'status'], name='accounting__recipie_27b8f1_idx'), models.Index(fields=['organization', '-issued_date'], name='accounting__organiz_b46fc4_idx')],
                'unique_together': {('organization', 'doc_number')},
            },
        ),
    ]
