from app.models.base import Base
from app.models.core import (
    Client,
    ClientCategory,
    ClientDebt,
    Currency,
    Department,
    DepartmentModule,
    MeasurementUnit,
    Organization,
    PoultryType,
    Warehouse,
    WorkspaceResource,
)
from app.models.egg import EggMonthlyAnalytics, EggProduction, EggShipment
from app.models.finance import (
    CashAccount,
    CashTransaction,
    DebtPayment,
    Expense,
    ExpenseCategory,
    SupplierDebt,
)
from app.models.hr import Employee, Permission, Position, Role, employee_roles, role_permissions
from app.models.inventory import StockMovement
from app.models.incubation import (
    ChickShipment,
    FactoryMonthlyAnalytics,
    IncubationBatch,
    IncubationMonthlyAnalytics,
    IncubationRun,
)
from app.models.feed import (
    FeedIngredient,
    FeedFormula,
    FeedFormulaIngredient,
    FeedMonthlyAnalytics,
    FeedProductionBatch,
    FeedProductionQualityCheck,
    FeedProductShipment,
    FeedRawArrival,
    FeedRawConsumption,
    FeedType,
)
from app.models.factory import (
    FactoryDailyLog,
    FactoryFlock,
    FactoryMedicineUsage,
    FactoryShipment,
    FactoryVaccinationPlan,
)
from app.models.medicine import MedicineBatch, MedicineType
from app.models.slaughter import (
    SlaughterMonthlyAnalytics,
    SlaughterProcessing,
    SlaughterQualityCheck,
    SlaughterSemiProduct,
    SlaughterSemiProductShipment,
)
from app.models.system import AuditLog, TelegramRecipient

__all__ = [
    "Base",
    "Organization",
    "DepartmentModule",
    "WorkspaceResource",
    "Employee",
    "Client",
    "ClientDebt",
    "Currency",
    "Department",
    "Warehouse",
    "EggProduction",
    "EggShipment",
    "EggMonthlyAnalytics",
    "ExpenseCategory",
    "Expense",
    "CashAccount",
    "CashTransaction",
    "SupplierDebt",
    "DebtPayment",
    "StockMovement",
    "Role",
    "Position",
    "Permission",
    "employee_roles",
    "role_permissions",
    "IncubationBatch",
    "IncubationRun",
    "ChickShipment",
    "IncubationMonthlyAnalytics",
    "FactoryMonthlyAnalytics",
    "PoultryType",
    "FeedType",
    "FeedIngredient",
    "FeedFormula",
    "FeedFormulaIngredient",
    "FeedMonthlyAnalytics",
    "FeedProductionBatch",
    "FeedProductionQualityCheck",
    "FeedProductShipment",
    "FeedRawArrival",
    "FeedRawConsumption",
    "SlaughterMonthlyAnalytics",
    "SlaughterProcessing",
    "SlaughterQualityCheck",
    "SlaughterSemiProduct",
    "SlaughterSemiProductShipment",
    "MedicineType",
    "MedicineBatch",
    "FactoryFlock",
    "FactoryDailyLog",
    "FactoryShipment",
    "FactoryMedicineUsage",
    "FactoryVaccinationPlan",
    "AuditLog",
    "TelegramRecipient",
]
