from app.models.base import Base
from app.models.core import (
    Client,
    ClientDebt,
    Currency,
    Department,
    DepartmentModule,
    Organization,
    PoultryType,
    Warehouse,
    WorkspaceResource,
)
from app.models.egg import EggMonthlyAnalytics, EggProduction, EggShipment
from app.models.finance import CashAccount, CashTransaction, Expense, ExpenseCategory
from app.models.hr import Employee, Permission, Position, Role, employee_roles, role_permissions
from app.models.inventory import StockMovement
from app.models.incubation import (
    ChickArrival,
    ChickShipment,
    FactoryMonthlyAnalytics,
    IncubationBatch,
    IncubationMonthlyAnalytics,
    IncubationRun,
)
from app.models.feed import (
    FeedArrival,
    FeedConsumption,
    FeedIngredient,
    FeedFormula,
    FeedFormulaIngredient,
    FeedProductionBatch,
    FeedRawArrival,
    FeedRawConsumption,
    FeedProductShipment,
    FeedType,
)
from app.models.medicine import MedicineArrival, MedicineBatch, MedicineConsumption, MedicineType
from app.models.slaughter import (
    SlaughterArrival,
    SlaughterProcessing,
    SlaughterSemiProduct,
    SlaughterSemiProductShipment,
)
from app.models.system import AuditLog

__all__ = [
    "Base",
    "Organization",
    "DepartmentModule",
    "WorkspaceResource",
    "Employee",
    "Client",
    "ClientDebt",
    "Currency",
    "Department",
    "Warehouse",
    "EggProduction",
    "EggShipment",
    "EggMonthlyAnalytics",
    "ExpenseCategory",
    "Expense",
    "CashAccount",
    "CashTransaction",
    "StockMovement",
    "Role",
    "Position",
    "Permission",
    "employee_roles",
    "role_permissions",
    "IncubationBatch",
    "IncubationRun",
    "ChickArrival",
    "ChickShipment",
    "IncubationMonthlyAnalytics",
    "FactoryMonthlyAnalytics",
    "PoultryType",
    "FeedType",
    "FeedIngredient",
    "FeedRawArrival",
    "FeedFormula",
    "FeedFormulaIngredient",
    "FeedProductionBatch",
    "FeedRawConsumption",
    "FeedProductShipment",
    "FeedArrival",
    "FeedConsumption",
    "SlaughterArrival",
    "SlaughterProcessing",
    "SlaughterSemiProduct",
    "SlaughterSemiProductShipment",
    "MedicineType",
    "MedicineArrival",
    "MedicineBatch",
    "MedicineConsumption",
    "AuditLog",
]
