# Generated by Django 5.1.3 on 2026-04-25 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoritePage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('href', models.CharField(help_text="Внутренний путь страницы, например '/sales' или '/finance/cashbox'.", max_length=255)),
                ('label', models.CharField(help_text='Snapshot человекочитаемого названия страницы из nav.ts.', max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Для будущей drag-reorder. Сейчас всегда 0, ordering MRU.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Закреплённая страница',
                'verbose_name_plural': 'Закреплённые страницы',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['user', 'sort_order'], name='users_userf_user_id_515743_idx')],
                'unique_together': {('user', 'href')},
            },
        ),
    ]
