# Generated by Django 5.1.3 on 2026-04-23 19:40

import apps.counterparties.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('kind', models.CharField(choices=[('supplier', 'Поставщик'), ('buyer', 'Покупатель'), ('other', 'Прочее')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('inn', models.CharField(blank=True, max_length=14, validators=[apps.counterparties.validators.validate_inn])),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('balance_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['code'],
            },
        ),
    ]
