# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparties', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['organization', 'kind'], name='counterpart_organiz_e98189_idx'),
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['name'], name='counterpart_name_6b080f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='counterparty',
            unique_together={('organization', 'code')},
        ),
    ]
