# Generated by Django 5.1.3 on 2026-05-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='credit_limit_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальный совокупный долг покупателя. Если непогашенная сумма confirmed-продаж + новая продажа > лимита — confirm_sale блокируется. NULL = без ограничения.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='max_overdue_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Максимальная допустимая просрочка по самому старому непогашенному счёту. Если есть счёт с просрочкой > этого значения — confirm_sale блокируется. NULL = без ограничения.', null=True),
        ),
    ]
