# Generated by Django 5.1.3 on 2026-05-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0003_counterparty_credit_limit_uzs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='opening_balance_date',
            field=models.DateField(blank=True, help_text='Дата на которую зафиксирован стартовый долг (день миграции). Используется в отчётах для фильтрации «до» / «после» миграции.', null=True),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='opening_debt_uzs',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Стартовый долг (миграция). Положительное = долг есть, отрицательное = предоплата. По умолчанию 0.', max_digits=18),
        ),
    ]
