# Generated by Django 5.1.3 on 2026-04-23 20:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_batch_withdrawal_period_ends'),
        ('feed', '0001_initial'),
        ('modules', '0003_seed_modules'),
        ('organizations', '0002_initial'),
        ('warehouses', '0003_alter_productionblock_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedlotBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('placed_date', models.DateField(db_index=True)),
                ('target_slaughter_date', models.DateField(blank=True, null=True)),
                ('target_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('2.500'), max_digits=6)),
                ('initial_heads', models.PositiveIntegerField()),
                ('current_heads', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('placed', 'Посажено'), ('growing', 'Откорм'), ('ready_slaughter', 'К съёму'), ('shipped', 'Передано на убой')], db_index=True, default='placed', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedlot_placements', to='batches.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('house_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedlot_batches', to='warehouses.productionblock')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedlot_batches', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedlot_batches', to='organizations.organization')),
                ('technologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedlot_batches_supervised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Партия откорма',
                'verbose_name_plural': 'Партии откорма',
                'ordering': ['-placed_date', 'doc_number'],
            },
        ),
        migrations.CreateModel(
            name='DailyWeighing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('day_of_age', models.PositiveSmallIntegerField()),
                ('sample_size', models.PositiveIntegerField()),
                ('avg_weight_kg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('gain_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feedlot_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighings', to='feedlot.feedlotbatch')),
            ],
            options={
                'verbose_name': 'Контрольное взвешивание',
                'verbose_name_plural': 'Контрольные взвешивания',
                'ordering': ['feedlot_batch', 'day_of_age'],
            },
        ),
        migrations.CreateModel(
            name='FeedlotFeedConsumption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_from_day', models.PositiveSmallIntegerField()),
                ('period_to_day', models.PositiveSmallIntegerField()),
                ('feed_type', models.CharField(choices=[('start', 'Старт'), ('growth', 'Рост'), ('finish', 'Финиш')], db_index=True, max_length=16)),
                ('total_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('per_head_g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('period_fcr', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('feed_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedlot_consumption_periods', to='feed.feedbatch')),
                ('feedlot_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_consumption_periods', to='feedlot.feedlotbatch')),
            ],
            options={
                'verbose_name': 'Расход корма (откорм)',
                'verbose_name_plural': 'Расход корма (откорм)',
                'ordering': ['feedlot_batch', 'period_from_day'],
            },
        ),
        migrations.CreateModel(
            name='FeedlotMortality',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('day_of_age', models.PositiveSmallIntegerField()),
                ('dead_count', models.PositiveIntegerField()),
                ('cause', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('feedlot_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='feedlot.feedlotbatch')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Падёж (откорм)',
                'verbose_name_plural': 'Падёж (откорм)',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='feedlotbatch',
            index=models.Index(fields=['organization', 'status'], name='feedlot_fee_organiz_601f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedlotbatch',
            index=models.Index(fields=['house_block', 'status'], name='feedlot_fee_house_b_da100f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedlotbatch',
            index=models.Index(fields=['batch'], name='feedlot_fee_batch_i_515049_idx'),
        ),
        migrations.AddIndex(
            model_name='feedlotbatch',
            index=models.Index(fields=['organization', '-placed_date'], name='feedlot_fee_organiz_7a7547_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedlotbatch',
            unique_together={('organization', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='dailyweighing',
            index=models.Index(fields=['feedlot_batch', '-date'], name='feedlot_dai_feedlot_ceb117_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyweighing',
            unique_together={('feedlot_batch', 'day_of_age')},
        ),
        migrations.AddIndex(
            model_name='feedlotfeedconsumption',
            index=models.Index(fields=['feedlot_batch', 'feed_type'], name='feedlot_fee_feedlot_d9ecae_idx'),
        ),
        migrations.AddIndex(
            model_name='feedlotfeedconsumption',
            index=models.Index(fields=['feed_batch'], name='feedlot_fee_feed_ba_fe0e72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedlotfeedconsumption',
            unique_together={('feedlot_batch', 'period_from_day', 'feed_type')},
        ),
        migrations.AddIndex(
            model_name='feedlotmortality',
            index=models.Index(fields=['feedlot_batch', '-date'], name='feedlot_fee_feedlot_69605d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedlotmortality',
            unique_together={('feedlot_batch', 'date')},
        ),
    ]
