# Generated by Django 5.1.3 on 2026-04-23 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('post', 'Проведение'), ('unpost', 'Отмена проведения'), ('login', 'Вход'), ('logout', 'Выход'), ('export', 'Экспорт'), ('import', 'Импорт'), ('permission_change', 'Изменение прав'), ('other', 'Прочее')], max_length=32)),
                ('action_verb', models.CharField(blank=True, max_length=64)),
                ('entity_object_id', models.UUIDField(blank=True, null=True)),
                ('entity_repr', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('diff', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
