# Generated by Django 5.1.3 on 2026-04-23 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_batch_withdrawal_period_ends'),
        ('modules', '0003_seed_modules'),
        ('nomenclature', '0002_initial'),
        ('organizations', '0002_initial'),
        ('warehouses', '0003_alter_productionblock_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaughterShift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('shift_date', models.DateField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('live_heads_received', models.PositiveIntegerField()),
                ('live_weight_kg_total', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'В работе'), ('closed', 'Закрыта'), ('posted', 'Проведена'), ('cancelled', 'Отменена')], db_index=True, default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('foreman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_shifts_led', to=settings.AUTH_USER_MODEL)),
                ('line_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_shifts', to='warehouses.productionblock')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_shifts', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_shifts', to='organizations.organization')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_shifts', to='batches.batch')),
            ],
            options={
                'verbose_name': 'Смена убоя',
                'verbose_name_plural': 'Смены убоя',
                'ordering': ['-shift_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SlaughterQualityCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carcass_defect_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trauma_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cooling_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vet_inspection_passed', models.BooleanField(default=False)),
                ('inspected_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_quality_inspections', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check', to='slaughter.slaughtershift')),
            ],
            options={
                'verbose_name': 'Контроль качества смены',
                'verbose_name_plural': 'Контроль качества смен',
            },
        ),
        migrations.CreateModel(
            name='SlaughterLabTest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator', models.CharField(db_index=True, max_length=64)),
                ('normal_range', models.CharField(max_length=64)),
                ('actual_value', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'В работе'), ('passed', 'Норма'), ('failed', 'Отклонение')], db_index=True, default='pending', max_length=16)),
                ('sampled_at', models.DateTimeField(blank=True, null=True)),
                ('result_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='slaughter.slaughtershift')),
            ],
            options={
                'verbose_name': 'Лаб. показатель смены',
                'verbose_name_plural': 'Лаб. показатели смен',
                'ordering': ['shift', 'indicator'],
            },
        ),
        migrations.CreateModel(
            name='SlaughterYield',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('share_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_yields', to='nomenclature.nomenclatureitem')),
                ('output_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_output_of', to='batches.batch')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='slaughter.slaughtershift')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.unit')),
            ],
            options={
                'verbose_name': 'Выход продукции',
                'verbose_name_plural': 'Выход продукции',
                'ordering': ['shift', 'nomenclature'],
            },
        ),
        migrations.AddIndex(
            model_name='slaughtershift',
            index=models.Index(fields=['organization', 'status'], name='slaughter_s_organiz_cf42a3_idx'),
        ),
        migrations.AddIndex(
            model_name='slaughtershift',
            index=models.Index(fields=['line_block', 'shift_date'], name='slaughter_s_line_bl_941589_idx'),
        ),
        migrations.AddIndex(
            model_name='slaughtershift',
            index=models.Index(fields=['source_batch'], name='slaughter_s_source__03aaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='slaughtershift',
            index=models.Index(fields=['organization', '-shift_date'], name='slaughter_s_organiz_1a8f56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slaughtershift',
            unique_together={('organization', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='slaughterlabtest',
            index=models.Index(fields=['shift', 'status'], name='slaughter_s_shift_i_9edc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='slaughterlabtest',
            index=models.Index(fields=['status'], name='slaughter_s_status_56488a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slaughterlabtest',
            unique_together={('shift', 'indicator')},
        ),
        migrations.AddIndex(
            model_name='slaughteryield',
            index=models.Index(fields=['shift'], name='slaughter_s_shift_i_bb061c_idx'),
        ),
        migrations.AddIndex(
            model_name='slaughteryield',
            index=models.Index(fields=['output_batch'], name='slaughter_s_output__65b68b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slaughteryield',
            unique_together={('shift', 'nomenclature')},
        ),
    ]
