# Generated by Django 5.1.3 on 2026-04-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_withdrawal_period_ends'),
        ('nomenclature', '0006_seed_module_categories'),
        ('slaughter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slaughteryield',
            options={'ordering': ['shift', 'nomenclature', 'grade'], 'verbose_name': 'Выход продукции', 'verbose_name_plural': 'Выход продукции'},
        ),
        migrations.AlterUniqueTogether(
            name='slaughteryield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='slaughterqualitycheck',
            name='confiscation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% конфискованной продукции по результатам вет-контроля.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='slaughteryield',
            name='grade',
            field=models.CharField(choices=[('grade_1', '1 сорт'), ('grade_2', '2 сорт'), ('substandard', 'Некондиция')], db_index=True, default='grade_1', help_text='Сортность продукции (1 сорт / 2 сорт / некондиция).', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='slaughteryield',
            unique_together={('shift', 'nomenclature', 'grade')},
        ),
        migrations.AddIndex(
            model_name='slaughteryield',
            index=models.Index(fields=['shift', 'grade'], name='slaughter_s_shift_i_de1307_idx'),
        ),
    ]
