# Generated by Django 5.1.3 on 2026-05-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_default_org_name'),
        ('tgbot', '0002_seed_debt_reminder_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tglink',
            name='active_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization'),
        ),
    ]
