# Generated by Django 5.1.3 on 2026-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_tglink_active_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='tglink',
            name='digest_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
