# Generated by Django 5.1.3 on 2026-05-08 04:23

import apps.tgbot.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_default_org_name'),
        ('tgbot', '0009_reschedule_evening_briefs_and_excel_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgWizardSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('wizard', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(default=apps.tgbot.models._wizard_expires)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TG wizard сессия',
                'verbose_name_plural': 'TG wizard сессии',
            },
        ),
    ]
