# Generated by Django 5.1.3 on 2026-05-12 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0004_counterparty_opening_balance_date_and_more'),
        ('organizations', '0004_rename_default_org_name'),
        ('tgbot', '0010_tgwizardsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('text', models.TextField()),
                ('source', models.CharField(choices=[('debt_reminder', 'Напоминание о долге'), ('tg_invite', 'Приглашение в TG'), ('system', 'Системное'), ('other', 'Прочее')], db_index=True, default='other', max_length=24)),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка')], db_index=True, default='sent', max_length=16)),
                ('error_msg', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_messages', to='counterparties.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_messages', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_messages_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TG-сообщение',
                'verbose_name_plural': 'TG-сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='tgbot_tgmes_organiz_0b1453_idx'), models.Index(fields=['counterparty', '-created_at'], name='tgbot_tgmes_counter_212cc0_idx'), models.Index(fields=['source', '-created_at'], name='tgbot_tgmes_source_9fab37_idx')],
            },
        ),
    ]
