# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.organizationmembership'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rbac.role'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleaccessoverride',
            unique_together={('membership', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('membership', 'role')},
        ),
    ]
