# Generated by Django 5.1.3 on 2026-04-30 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_default_org_name'),
        ('rbac', '0005_seed_demo_users_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScopeAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('warehouse', 'Склад'), ('production_block', 'Производственный блок')], db_index=True, max_length=24)),
                ('scope_id', models.UUIDField(db_index=True, help_text='UUID конкретного объекта (warehouse или production_block).')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scope_assignments', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Назначение row-level scope',
                'verbose_name_plural': 'Назначения row-level scope',
                'indexes': [models.Index(fields=['organization', 'user', 'scope_type'], name='rbac_usersc_organiz_c356ed_idx')],
                'unique_together': {('organization', 'user', 'scope_type', 'scope_id')},
            },
        ),
    ]
