# Generated by Django 5.1.3 on 2026-04-23 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_batch_withdrawal_period_ends'),
        ('counterparties', '0002_initial'),
        ('matochnik', '0001_initial'),
        ('modules', '0003_seed_modules'),
        ('nomenclature', '0002_initial'),
        ('organizations', '0002_initial'),
        ('purchases', '0004_purchaseorder_batch_and_more'),
        ('warehouses', '0003_alter_productionblock_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('direction', models.CharField(choices=[('broiler', 'Бройлер'), ('layer', 'Несушка'), ('parent', 'Родительское стадо')], db_index=True, max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_schedules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Схема вакцинации',
                'verbose_name_plural': 'Схемы вакцинации',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VetDrug',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_type', models.CharField(choices=[('vaccine', 'Вакцина'), ('antibiotic', 'Антибиотик'), ('vitamin', 'Витамин'), ('electrolyte', 'Электролит'), ('other', 'Прочее')], db_index=True, max_length=16)),
                ('administration_route', models.CharField(choices=[('injection', 'Инъекция'), ('oral', 'Оральное'), ('drinking_water', 'С водой'), ('spray', 'Спрей'), ('other', 'Прочее')], max_length=16)),
                ('default_withdrawal_days', models.PositiveSmallIntegerField(default=0)),
                ('storage_conditions', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_drugs', to='modules.module')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_drug_cards', to='nomenclature.nomenclatureitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_drugs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Ветпрепарат',
                'verbose_name_plural': 'Ветпрепараты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationScheduleItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_age', models.PositiveSmallIntegerField()),
                ('dose_per_head', models.DecimalField(decimal_places=4, max_digits=10)),
                ('administration_route', models.CharField(blank=True, choices=[('injection', 'Инъекция'), ('oral', 'Оральное'), ('drinking_water', 'С водой'), ('spray', 'Спрей'), ('other', 'Прочее')], max_length=16, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vet.vaccinationschedule')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='vet.vetdrug')),
            ],
            options={
                'verbose_name': 'Строка схемы вакцинации',
                'verbose_name_plural': 'Строки схемы вакцинации',
                'ordering': ['schedule', 'day_of_age'],
            },
        ),
        migrations.CreateModel(
            name='VetStockBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('lot_number', models.CharField(db_index=True, max_length=64)),
                ('received_date', models.DateField(db_index=True)),
                ('expiration_date', models.DateField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('current_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price_per_unit_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('quarantine', 'На карантине'), ('expiring_soon', 'Скоро истекает'), ('expired', 'Истекла'), ('depleted', 'Исчерпана'), ('recalled', 'Отозвана')], db_index=True, default='quarantine', max_length=16)),
                ('quarantine_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_batches', to='vet.vetdrug')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_stock_batches', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_stock_batches', to='organizations.organization')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vet_stock_batches', to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_stock_batches', to='counterparties.counterparty')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.unit')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_stock_batches', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Партия ветпрепарата',
                'verbose_name_plural': 'Партии ветпрепаратов',
                'ordering': ['-received_date', 'doc_number'],
            },
        ),
        migrations.CreateModel(
            name='VetTreatmentLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('treatment_date', models.DateField(db_index=True)),
                ('dose_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('heads_treated', models.PositiveIntegerField()),
                ('withdrawal_period_days', models.PositiveSmallIntegerField(default=0)),
                ('administration_route', models.CharField(blank=True, choices=[('injection', 'Инъекция'), ('oral', 'Оральное'), ('drinking_water', 'С водой'), ('spray', 'Спрей'), ('other', 'Прочее')], max_length=16, null=True)),
                ('indication', models.CharField(choices=[('routine', 'Плановая обработка'), ('prophylaxis', 'Профилактика'), ('therapy', 'Лечение'), ('emergency', 'Экстренно')], db_index=True, max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_logs', to='vet.vetdrug')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_treatment_logs', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_treatment_logs', to='organizations.organization')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_logs', to='vet.vaccinationscheduleitem')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumed_in_treatments', to='vet.vetstockbatch')),
                ('target_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vet_treatments', to='batches.batch')),
                ('target_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_treatments', to='warehouses.productionblock')),
                ('target_herd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vet_treatments', to='matochnik.breedingherd')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.unit')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_treatments_supervised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал применения',
                'verbose_name_plural': 'Журнал применений',
                'ordering': ['-treatment_date', 'doc_number'],
            },
        ),
        migrations.AddIndex(
            model_name='vaccinationschedule',
            index=models.Index(fields=['organization', 'direction'], name='vet_vaccina_organiz_74c50a_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationschedule',
            index=models.Index(fields=['organization', 'is_active'], name='vet_vaccina_organiz_6646ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinationschedule',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='vetdrug',
            index=models.Index(fields=['organization', 'is_active'], name='vet_vetdrug_organiz_c0050f_idx'),
        ),
        migrations.AddIndex(
            model_name='vetdrug',
            index=models.Index(fields=['organization', 'drug_type'], name='vet_vetdrug_organiz_ee098f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vetdrug',
            unique_together={('organization', 'nomenclature')},
        ),
        migrations.AddIndex(
            model_name='vaccinationscheduleitem',
            index=models.Index(fields=['schedule', 'day_of_age'], name='vet_vaccina_schedul_f29584_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinationscheduleitem',
            unique_together={('schedule', 'day_of_age', 'drug')},
        ),
        migrations.AddIndex(
            model_name='vetstockbatch',
            index=models.Index(fields=['organization', 'status'], name='vet_vetstoc_organiz_7427b8_idx'),
        ),
        migrations.AddIndex(
            model_name='vetstockbatch',
            index=models.Index(fields=['drug', 'status'], name='vet_vetstoc_drug_id_def978_idx'),
        ),
        migrations.AddIndex(
            model_name='vetstockbatch',
            index=models.Index(fields=['organization', '-received_date'], name='vet_vetstoc_organiz_d2c1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='vetstockbatch',
            index=models.Index(fields=['warehouse', 'status'], name='vet_vetstoc_warehou_420501_idx'),
        ),
        migrations.AddIndex(
            model_name='vetstockbatch',
            index=models.Index(fields=['status', 'expiration_date'], name='vet_vetstoc_status_bfe418_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vetstockbatch',
            unique_together={('organization', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='vettreatmentlog',
            index=models.Index(fields=['organization', '-treatment_date'], name='vet_vettrea_organiz_4d13f8_idx'),
        ),
        migrations.AddIndex(
            model_name='vettreatmentlog',
            index=models.Index(fields=['target_batch', '-treatment_date'], name='vet_vettrea_target__9b219b_idx'),
        ),
        migrations.AddIndex(
            model_name='vettreatmentlog',
            index=models.Index(fields=['target_herd', '-treatment_date'], name='vet_vettrea_target__e9862e_idx'),
        ),
        migrations.AddIndex(
            model_name='vettreatmentlog',
            index=models.Index(fields=['drug', '-treatment_date'], name='vet_vettrea_drug_id_e9bf57_idx'),
        ),
        migrations.AddIndex(
            model_name='vettreatmentlog',
            index=models.Index(fields=['stock_batch'], name='vet_vettrea_stock_b_b3b043_idx'),
        ),
        migrations.AddIndex(
            model_name='vettreatmentlog',
            index=models.Index(fields=['organization', 'indication'], name='vet_vettrea_organiz_4b7c6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vettreatmentlog',
            unique_together={('organization', 'doc_number')},
        ),
    ]
