# Generated by Django 5.1.3 on 2026-04-25 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_initial'),
        ('modules', '0006_seed_sales_module'),
        ('nomenclature', '0004_seed_slaughter_skus'),
        ('organizations', '0003_organizationmembership_work_phone_and_more'),
        ('purchases', '0005_purchaseorder_paid_amount_uzs_and_more'),
        ('vet', '0001_initial'),
        ('warehouses', '0005_seed_default_blocks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDeviceToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text='Описание устройства/точки продаж, например «Магазин Юнусабад».', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Токен продавца',
                'verbose_name_plural': 'Токены продавцов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='vetstockbatch',
            unique_together={('organization', 'doc_number')},
        ),
        migrations.AddField(
            model_name='vetstockbatch',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный штрих-код лота для розничной продажи и сканирования.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vetstockbatch',
            name='recall_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vetstockbatch',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vettreatmentlog',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vettreatmentlog',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vettreatmentlog',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vetstockbatch',
            unique_together={('organization', 'barcode'), ('organization', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='vetstockbatch',
            index=models.Index(fields=['organization', 'barcode'], name='vet_vetstoc_organiz_54d5fa_idx'),
        ),
        migrations.AddField(
            model_name='sellerdevicetoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerdevicetoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_tokens', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='sellerdevicetoken',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerdevicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sellerdevicetoken',
            index=models.Index(fields=['organization', 'is_active'], name='vet_sellerd_organiz_4c9e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdevicetoken',
            index=models.Index(fields=['user', 'is_active'], name='vet_sellerd_user_id_eb2895_idx'),
        ),
    ]
