# Generated by Django 5.1.3 on 2026-05-04 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_seed_sales_module'),
        ('nomenclature', '0006_seed_module_categories'),
        ('organizations', '0004_rename_default_org_name'),
        ('vet', '0004_vettreatment_acknowledged'),
        ('warehouses', '0006_stockmovement_shrinkage_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VetAccessory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('cost_per_unit_uzs', models.DecimalField(decimal_places=2, default=0, help_text='Текущая себестоимость единицы (weighted-avg при приёмке). Используется в Cr-проводке при продаже.', max_digits=18)),
                ('sale_price_uzs', models.DecimalField(decimal_places=2, default=0, help_text='Текущая розничная цена. Меняется без переоценки склада. В SaleItem можно переопределить через unit_price_uzs.', max_digits=18)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Штрих-код для розничного скан-фло. Авто-генерится при create если не задан вручную (например при штрихкоде поставщика).', max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_accessories', to='modules.module')),
                ('nomenclature', models.ForeignKey(help_text='Номенклатурная карточка (sku/name/unit). Категория должна указывать на 41.01, иначе fallback в проводке.', on_delete=django.db.models.deletion.PROTECT, related_name='vet_accessories', to='nomenclature.nomenclatureitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_accessories', to='organizations.organization')),
                ('warehouse', models.ForeignKey(help_text='Склад где физически лежит товар (модуль = vet).', on_delete=django.db.models.deletion.PROTECT, related_name='vet_accessories', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Аксессуар вет-аптеки',
                'verbose_name_plural': 'Аксессуары вет-аптеки',
                'ordering': ['nomenclature__sku'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='vet_vetacce_organiz_9418fe_idx'), models.Index(fields=['warehouse', 'is_active'], name='vet_vetacce_warehou_41cefd_idx'), models.Index(fields=['organization', 'barcode'], name='vet_vetacce_organiz_0c2a4e_idx')],
                'unique_together': {('organization', 'barcode')},
            },
        ),
    ]
