# Generated by Django 5.1.3 on 2026-05-04 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_seed_sales_module'),
        ('nomenclature', '0006_seed_module_categories'),
        ('organizations', '0004_rename_default_org_name'),
        ('vet', '0006_seed_accessories_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vetdrug',
            unique_together={('organization', 'nomenclature')},
        ),
        migrations.AddField(
            model_name='vetdrug',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Штрих-код SKU (для shelf-tag — этикетка на полке). Авто-генерится при create если не задан вручную. Не путать с barcode у VetStockBatch (там штрих-код конкретного лота для розничной продажи).', max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vetdrug',
            unique_together={('organization', 'barcode'), ('organization', 'nomenclature')},
        ),
        migrations.AddIndex(
            model_name='vetdrug',
            index=models.Index(fields=['organization', 'barcode'], name='vet_vetdrug_organiz_06adc8_idx'),
        ),
    ]
