# Generated by Django 5.1.3 on 2026-05-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0007_alter_vetdrug_unique_together_vetdrug_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetdrug',
            name='storage_temp_max_c',
            field=models.SmallIntegerField(blank=True, help_text='Максимальная температура хранения, °C (целое со знаком).', null=True),
        ),
        migrations.AddField(
            model_name='vetdrug',
            name='storage_temp_min_c',
            field=models.SmallIntegerField(blank=True, help_text='Минимальная температура хранения, °C (целое со знаком).', null=True),
        ),
    ]
