# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('numeric_code', models.CharField(blank=True, max_length=3)),
                ('name_ru', models.CharField(max_length=64)),
                ('name_en', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('nominal', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(default='cbu.uz', max_length=32)),
                ('fetched_at', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='currency.currency')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date', 'currency__code'],
                'indexes': [models.Index(fields=['currency', '-date'], name='currency_ex_currenc_e747c2_idx')],
                'unique_together': {('currency', 'date', 'source')},
            },
        ),
    ]
