# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('nomenclature', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='nomenclature.category'),
        ),
        migrations.AddField(
            model_name='nomenclatureitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='nomenclature.category'),
        ),
        migrations.AddField(
            model_name='nomenclatureitem',
            name='default_gl_subaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='accounting.glsubaccount'),
        ),
        migrations.AddField(
            model_name='nomenclatureitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomenclature_items', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='nomenclatureitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='nomenclature.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='nomenclatureitem',
            unique_together={('organization', 'sku')},
        ),
    ]
