# Generated by Django 5.1.3 on 2026-04-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclatureitem',
            name='base_moisture_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Базисная влажность %. Используется при приёмке сырья для расчёта зачётного веса по формуле Дюваля. Зерно/ГОСТ 13586.5 — 14%, шрот — 12%, премикс — 10%.', max_digits=5, null=True),
        ),
    ]
