# Generated by Django 5.1.3 on 2026-04-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_seed_expense_articles'),
        ('modules', '0006_seed_sales_module'),
        ('nomenclature', '0004_seed_slaughter_skus'),
        ('organizations', '0003_organizationmembership_work_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='module',
            field=models.ForeignKey(blank=True, help_text='К какому модулю относится категория. Если NULL — категория общая (не привязана). Используется для фильтрации SKU в формах модулей.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nomenclature_categories', to='modules.module'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organization', 'module'], name='nomenclatur_organiz_7b0b38_idx'),
        ),
    ]
