# Generated by Django 5.1.3 on 2026-04-23 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_batch_withdrawal_period_ends'),
        ('counterparties', '0002_initial'),
        ('feed', '0001_initial'),
        ('modules', '0003_seed_modules'),
        ('organizations', '0002_initial'),
        ('warehouses', '0003_alter_productionblock_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingHerd',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('direction', models.CharField(choices=[('broiler_parent', 'Бройлерное родительское'), ('layer_parent', 'Яичное родительское')], db_index=True, max_length=16)),
                ('placed_at', models.DateField(db_index=True)),
                ('initial_heads', models.PositiveIntegerField()),
                ('current_heads', models.PositiveIntegerField()),
                ('age_weeks_at_placement', models.PositiveSmallIntegerField()),
                ('current_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('growing', 'Разгон'), ('producing', 'Продуктив'), ('depopulated', 'Снято')], db_index=True, default='growing', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeding_herds', to='warehouses.productionblock')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeding_herds', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeding_herds', to='organizations.organization')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spawned_breeding_herds', to='batches.batch')),
                ('source_counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='counterparties.counterparty')),
                ('technologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matochnik_herds_supervised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Родительское стадо',
                'verbose_name_plural': 'Родительские стада',
                'ordering': ['-placed_at', 'doc_number'],
            },
        ),
        migrations.CreateModel(
            name='BreedingFeedConsumption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=12)),
                ('per_head_g', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('feed_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matochnik_consumption_records', to='feed.feedbatch')),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_consumption_records', to='matochnik.breedingherd')),
            ],
            options={
                'verbose_name': 'Суточный расход корма (маточник)',
                'verbose_name_plural': 'Суточный расход корма (маточник)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BreedingMortality',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('dead_count', models.PositiveIntegerField()),
                ('cause', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortality_records', to='matochnik.breedingherd')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Падёж стада',
                'verbose_name_plural': 'Падёж стада',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyEggProduction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('eggs_collected', models.PositiveIntegerField()),
                ('unfit_eggs', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_egg_records', to='matochnik.breedingherd')),
                ('outgoing_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_production_records', to='batches.batch')),
            ],
            options={
                'verbose_name': 'Суточный яйцесбор',
                'verbose_name_plural': 'Суточный яйцесбор',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='breedingherd',
            index=models.Index(fields=['organization', 'status'], name='matochnik_b_organiz_85fe40_idx'),
        ),
        migrations.AddIndex(
            model_name='breedingherd',
            index=models.Index(fields=['organization', '-placed_at'], name='matochnik_b_organiz_bacc23_idx'),
        ),
        migrations.AddIndex(
            model_name='breedingherd',
            index=models.Index(fields=['block', 'status'], name='matochnik_b_block_i_2e617a_idx'),
        ),
        migrations.AddIndex(
            model_name='breedingherd',
            index=models.Index(fields=['direction', 'status'], name='matochnik_b_directi_b731f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breedingherd',
            unique_together={('organization', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='breedingfeedconsumption',
            index=models.Index(fields=['herd', '-date'], name='matochnik_b_herd_id_e48ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='breedingfeedconsumption',
            index=models.Index(fields=['feed_batch'], name='matochnik_b_feed_ba_49e815_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breedingfeedconsumption',
            unique_together={('herd', 'date', 'feed_batch')},
        ),
        migrations.AddIndex(
            model_name='breedingmortality',
            index=models.Index(fields=['herd', '-date'], name='matochnik_b_herd_id_ceb844_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breedingmortality',
            unique_together={('herd', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailyeggproduction',
            index=models.Index(fields=['herd', '-date'], name='matochnik_d_herd_id_be3c36_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyeggproduction',
            index=models.Index(fields=['outgoing_batch'], name='matochnik_d_outgoin_f5dc06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyeggproduction',
            unique_together={('herd', 'date')},
        ),
    ]
