# Generated by Django 5.1.3 on 2026-04-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matochnik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingmortality',
            name='cause_detail',
            field=models.CharField(blank=True, help_text='Свободный комментарий (диагноз, препарат и т.п.).', max_length=128),
        ),
        migrations.AlterField(
            model_name='breedingmortality',
            name='cause',
            field=models.CharField(choices=[('disease', 'Болезнь'), ('trauma', 'Травма'), ('heat_stress', 'Тепловой стресс'), ('suffocation', 'Асфиксия'), ('culling', 'Выбраковка'), ('other', 'Иное'), ('unknown', 'Не установлена')], db_index=True, default='unknown', max_length=16),
        ),
    ]
