# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('core', 'Ядро'), ('matochnik', 'Маточник'), ('incubation', 'Инкубация'), ('feedlot', 'Фабрика откорма'), ('slaughter', 'Убойня'), ('feed', 'Корма'), ('vet', 'Вет. аптека'), ('stock', 'Склад и движения'), ('ledger', 'Проводки'), ('reports', 'Отчёты'), ('purchases', 'Закупки'), ('admin', 'Администрирование')], max_length=32, unique=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_activations', to='modules.module')),
            ],
            options={
                'verbose_name': 'Модуль организации',
                'verbose_name_plural': 'Модули организаций',
            },
        ),
    ]
