# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_modules', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='organizationmodule',
            index=models.Index(fields=['organization', 'is_enabled'], name='modules_org_organiz_442375_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmodule',
            unique_together={('organization', 'module')},
        ),
    ]
