# Generated by Django 5.1.3 on 2026-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_seed_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='kind',
            field=models.CharField(choices=[('core', 'Ядро'), ('matochnik', 'Маточник'), ('incubation', 'Инкубация'), ('feedlot', 'Фабрика откорма'), ('slaughter', 'Убойня'), ('feed', 'Корма'), ('vet', 'Вет. аптека'), ('stock', 'Склад и движения'), ('ledger', 'Проводки'), ('reports', 'Отчёты'), ('purchases', 'Закупки'), ('sales', 'Продажи'), ('admin', 'Администрирование')], max_length=32, unique=True),
        ),
    ]
