# Generated by Django 5.1.3 on 2026-04-23 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_batch_withdrawal_period_ends'),
        ('modules', '0003_seed_modules'),
        ('organizations', '0002_initial'),
        ('warehouses', '0003_alter_productionblock_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncubationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('loaded_date', models.DateField(db_index=True)),
                ('expected_hatch_date', models.DateField()),
                ('actual_hatch_date', models.DateField(blank=True, null=True)),
                ('eggs_loaded', models.PositiveIntegerField()),
                ('fertile_eggs', models.PositiveIntegerField(blank=True, null=True)),
                ('hatched_count', models.PositiveIntegerField(blank=True, null=True)),
                ('discarded_count', models.PositiveIntegerField(blank=True, null=True)),
                ('days_total', models.PositiveSmallIntegerField(default=21)),
                ('current_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('incubating', 'Инкубация'), ('hatching', 'Вывод'), ('transferred', 'Передано'), ('cancelled', 'Отменено')], db_index=True, default='incubating', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incubation_runs', to='batches.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hatcher_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incubation_runs_as_hatcher', to='warehouses.productionblock')),
                ('incubator_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incubation_runs_as_incubator', to='warehouses.productionblock')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incubation_runs', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incubation_runs', to='organizations.organization')),
                ('technologist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incubation_runs_supervised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инкубационная партия',
                'verbose_name_plural': 'Инкубационные партии',
                'ordering': ['-loaded_date', 'doc_number'],
            },
        ),
        migrations.CreateModel(
            name='IncubationRegimeDay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.PositiveSmallIntegerField()),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('egg_turns_per_day', models.PositiveSmallIntegerField(default=0)),
                ('actual_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_humidity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('observed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regime_days', to='incubation.incubationrun')),
            ],
            options={
                'verbose_name': 'День режима инкубации',
                'verbose_name_plural': 'Режим инкубации',
                'ordering': ['run', 'day'],
            },
        ),
        migrations.CreateModel(
            name='MirageInspection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspection_date', models.DateField(db_index=True)),
                ('day_of_incubation', models.PositiveSmallIntegerField()),
                ('inspected_count', models.PositiveIntegerField()),
                ('fertile_count', models.PositiveIntegerField()),
                ('discarded_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mirage_inspections', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirage_inspections', to='incubation.incubationrun')),
            ],
            options={
                'verbose_name': 'Овоскопия',
                'verbose_name_plural': 'Овоскопии',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='incubationrun',
            index=models.Index(fields=['organization', 'status'], name='incubation__organiz_342607_idx'),
        ),
        migrations.AddIndex(
            model_name='incubationrun',
            index=models.Index(fields=['incubator_block', 'status'], name='incubation__incubat_cca762_idx'),
        ),
        migrations.AddIndex(
            model_name='incubationrun',
            index=models.Index(fields=['batch'], name='incubation__batch_i_3e9a07_idx'),
        ),
        migrations.AddIndex(
            model_name='incubationrun',
            index=models.Index(fields=['organization', '-loaded_date'], name='incubation__organiz_dfb81b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incubationrun',
            unique_together={('organization', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='incubationregimeday',
            index=models.Index(fields=['run', 'day'], name='incubation__run_id_5ee2d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incubationregimeday',
            unique_together={('run', 'day')},
        ),
        migrations.AddIndex(
            model_name='mirageinspection',
            index=models.Index(fields=['run', '-inspection_date'], name='incubation__run_id_344b26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mirageinspection',
            unique_together={('run', 'inspection_date')},
        ),
    ]
