# Generated by Django 5.1.3 on 2026-04-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubationrun',
            name='eggs_broken_on_load',
            field=models.PositiveIntegerField(default=0, help_text='Яиц разбито/повреждено при закладке (вычитается из eggs_loaded).'),
        ),
    ]
