import { describe, expect, it } from 'vitest';

import type { CrudFieldMeta } from '@/shared/api/backend-crud';

import {
  EMPTY_TEXT,
  MASKED_PASSWORD_VALUE,
  applyAutoGeneratedCodeFields,
  buildAutoGeneratedCodeValue,
  buildFormValues,
  canExecuteModuleCrudAction,
  getDefaultInventoryItemTypeForModule,
  getDisplayValue,
  resolveResourceCategoryGroupId,
  shouldExposeResourceInModule,
  getTableFields,
} from './module-crud-page.helpers';

const buildField = (overrides: Partial<CrudFieldMeta>): CrudFieldMeta => ({
  name: 'id',
  label: 'ID',
  type: 'string',
  database_type: 'text',
  nullable: false,
  required: false,
  readonly: false,
  has_default: false,
  is_primary_key: false,
  is_foreign_key: false,
  reference: null,
  ...overrides,
});

describe('module crud password safety', () => {
  it('does not prefill password fields from existing records', () => {
    const fields = [
      buildField({ name: 'email', label: 'Email', type: 'string' }),
      buildField({ name: 'password', label: 'Password', type: 'string' }),
    ];

    const values = buildFormValues(fields, {
      email: 'sherzod@example.com',
      password: 'pbkdf2_sha256$260000$abc$hash',
    });

    expect(values.email).toBe('sherzod@example.com');
    expect(values.password).toBe(EMPTY_TEXT);
  });

  it('keeps password columns out of tables', () => {
    const fields = [
      buildField({ name: 'first_name', label: 'First name', type: 'string' }),
      buildField({ name: 'password', label: 'Password', type: 'string' }),
      buildField({ name: 'login', label: 'Login', type: 'string' }),
    ];

    const tableFields = getTableFields(fields, 'id');

    expect(tableFields.map((field) => field.name)).toEqual(['first_name', 'login']);
  });

  it('masks password values when a formatter has to render them', () => {
    const passwordField = buildField({ name: 'password', label: 'Password', type: 'string' });

    expect(
      getDisplayValue(passwordField, 'pbkdf2_sha256$260000$abc$hash', 'Yes', 'No', EMPTY_TEXT),
    ).toBe(MASKED_PASSWORD_VALUE);
  });

  it('generates code from name fields', () => {
    const fields = [
      buildField({ name: 'name', label: 'Name', type: 'string' }),
      buildField({ name: 'code', label: 'Code', type: 'string' }),
    ];

    expect(
      buildAutoGeneratedCodeValue(fields, { name: 'Broiler majmuasi', code: '' }, 'code'),
    ).toBe('BROILER-MAJMUASI');
  });

  it('generates dotted codes from resource and action fields', () => {
    const fields = [
      buildField({ name: 'resource', label: 'Resource', type: 'string' }),
      buildField({ name: 'action', label: 'Action', type: 'string' }),
      buildField({ name: 'code', label: 'Code', type: 'string' }),
    ];

    expect(
      buildAutoGeneratedCodeValue(
        fields,
        { resource: 'employee', action: 'read', code: '' },
        'code',
      ),
    ).toBe('employee.read');
  });

  it('does not overwrite a manually edited code value', () => {
    const fields = [
      buildField({ name: 'name', label: 'Name', type: 'string' }),
      buildField({ name: 'code', label: 'Code', type: 'string' }),
    ];

    const previousValues = {
      name: 'Broiler majmuasi',
      code: 'CUSTOM-CODE',
    };
    const nextValues = {
      name: 'Broiler maydoni',
      code: 'CUSTOM-CODE',
    };

    expect(applyAutoGeneratedCodeFields(fields, previousValues, nextValues, 'name').code).toBe(
      'CUSTOM-CODE',
    );
  });

  it('derives the default inventory item type from the current module', () => {
    expect(getDefaultInventoryItemTypeForModule('egg')).toBe('egg');
    expect(getDefaultInventoryItemTypeForModule('feed')).toBe('feed');
    expect(getDefaultInventoryItemTypeForModule('medicine')).toBe('medicine');
    expect(getDefaultInventoryItemTypeForModule('slaughter')).toBe('semi_product');
    expect(getDefaultInventoryItemTypeForModule('incubation')).toBe('chick');
    expect(getDefaultInventoryItemTypeForModule('factory')).toBe('chick');
  });
});

describe('module finance resource routing', () => {
  it('shows finance resources inside operational modules', () => {
    expect(
      shouldExposeResourceInModule('egg', { key: 'client-debts', apiModuleKey: 'core' }),
    ).toBe(true);
    expect(
      shouldExposeResourceInModule('feed', { key: 'cash-transactions', apiModuleKey: 'finance' }),
    ).toBe(true);
    expect(shouldExposeResourceInModule('core', { key: 'currencies' })).toBe(true);
  });

  it('classifies debt and currency resources as finance tabs', () => {
    expect(
      resolveResourceCategoryGroupId({
        key: 'client-debts',
        permissionPrefix: 'client_debt',
      }),
    ).toBe('finance');
    expect(
      resolveResourceCategoryGroupId({
        key: 'currencies',
        permissionPrefix: 'currency',
      }),
    ).toBe('finance');
  });
});

describe('module crud RBAC guards', () => {
  it('blocks actions when permission flags are missing', () => {
    const deniedAccess = {
      canCreateActiveResource: false,
      canEditRecordEntries: false,
      canDeleteActiveResource: false,
      canSendClientNotifications: false,
    };

    expect(canExecuteModuleCrudAction('create_record', deniedAccess)).toBe(false);
    expect(canExecuteModuleCrudAction('update_record', deniedAccess)).toBe(false);
    expect(canExecuteModuleCrudAction('delete_record', deniedAccess)).toBe(false);
    expect(canExecuteModuleCrudAction('stock_transfer', deniedAccess)).toBe(false);
    expect(canExecuteModuleCrudAction('client_notification', deniedAccess)).toBe(false);
  });

  it('allows actions only when corresponding permission flags are present', () => {
    expect(
      canExecuteModuleCrudAction('create_record', {
        canCreateActiveResource: true,
        canEditRecordEntries: false,
        canDeleteActiveResource: false,
        canSendClientNotifications: false,
      }),
    ).toBe(true);
    expect(
      canExecuteModuleCrudAction('update_record', {
        canCreateActiveResource: true,
        canEditRecordEntries: true,
        canDeleteActiveResource: false,
        canSendClientNotifications: false,
      }),
    ).toBe(true);
    expect(
      canExecuteModuleCrudAction('delete_record', {
        canCreateActiveResource: true,
        canEditRecordEntries: true,
        canDeleteActiveResource: true,
        canSendClientNotifications: false,
      }),
    ).toBe(true);
    expect(
      canExecuteModuleCrudAction('client_notification', {
        canCreateActiveResource: false,
        canEditRecordEntries: false,
        canDeleteActiveResource: false,
        canSendClientNotifications: true,
      }),
    ).toBe(true);
  });
});
