# Generated by Django 5.1.3 on 2026-04-23 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('counterparties', '0002_initial'),
        ('modules', '0002_initial'),
        ('nomenclature', '0002_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBlock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('matochnik', 'Корпус маточника'), ('incubation', 'Инкубационный шкаф'), ('hatcher', 'Выводной шкаф'), ('feedlot', 'Птичник откорма'), ('slaughter_line', 'Линия разделки'), ('warehouse', 'Склад'), ('vet_storage', 'Склад препаратов'), ('other', 'Прочее')], max_length=32)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nomenclature.unit')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_blocks', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_blocks', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Производственный блок',
                'verbose_name_plural': 'Производственные блоки',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('default_gl_subaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.glsubaccount')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='organizations.organization')),
                ('production_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='warehouses.productionblock')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('kind', models.CharField(choices=[('incoming', 'Приход'), ('outgoing', 'Расход'), ('transfer', 'Перемещение'), ('write_off', 'Списание')], max_length=16)),
                ('date', models.DateTimeField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('batch_id_stub', models.CharField(blank=True, max_length=64)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='counterparties.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='modules.module')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='nomenclature.nomenclatureitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organizations.organization')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='warehouses.warehouse')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Движение по складу',
                'verbose_name_plural': 'Движения по складу',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', '-date'], name='warehouses__organiz_a23dbf_idx'), models.Index(fields=['kind'], name='warehouses__kind_343626_idx'), models.Index(fields=['source_content_type', 'source_object_id'], name='warehouses__source__966484_idx')],
                'unique_together': {('organization', 'doc_number')},
            },
        ),
    ]
