# Generated by Django 5.1.3 on 2026-04-23 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('counterparties', '0002_initial'),
        ('modules', '0003_seed_modules'),
        ('nomenclature', '0002_initial'),
        ('organizations', '0002_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='batch_id_stub',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='batches.batch'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch'], name='warehouses__batch_i_4e5c0d_idx'),
        ),
    ]
