# Generated by Django 5.1.3 on 2026-04-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_remove_stockmovement_batch_id_stub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionblock',
            name='kind',
            field=models.CharField(choices=[('matochnik', 'Корпус маточника'), ('incubation', 'Инкубационный шкаф'), ('hatcher', 'Выводной шкаф'), ('feedlot', 'Птичник откорма'), ('slaughter_line', 'Линия разделки'), ('warehouse', 'Склад'), ('vet_storage', 'Склад препаратов'), ('mixer_line', 'Линия замеса'), ('storage_bin', 'Бункер готового комбикорма'), ('other', 'Прочее')], max_length=32),
        ),
    ]
