# Generated by Django 5.1.3 on 2026-04-23 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_journalentry_batch_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('counterparties', '0002_initial'),
        ('currency', '0001_initial'),
        ('modules', '0003_seed_modules'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('direction', models.CharField(choices=[('out', 'Оплата поставщику'), ('in', 'Поступление от покупателя')], db_index=True, max_length=8)),
                ('channel', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перечисление'), ('click', 'Click'), ('other', 'Прочее')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён'), ('posted', 'Проведён'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=16)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('amount_foreign', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cash_subaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.glsubaccount')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='currency.currency')),
                ('exchange_rate_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_payments', to='currency.exchangerate')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date', 'doc_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_object_id', models.UUIDField()),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Разнесение платежа',
                'verbose_name_plural': 'Разнесения платежей',
                'ordering': ['payment', 'target_content_type', 'target_object_id'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', '-date'], name='payments_pa_organiz_8c8564_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'direction', 'status'], name='payments_pa_organiz_1e721e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['counterparty', '-date'], name='payments_pa_counter_ed3527_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['channel', 'status'], name='payments_pa_channel_a06c92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('organization', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='payments_pa_target__c40e95_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment'], name='payments_pa_payment_bc6702_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'target_content_type', 'target_object_id')},
        ),
    ]
