# Generated by Django 5.1.3 on 2026-04-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_seed_opex_accounts'),
        ('counterparties', '0002_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='contra_subaccount',
            field=models.ForeignKey(blank=True, help_text='Для прочих операций: субсчёт расхода/дохода (20.XX, 26.XX, 70, 91.XX).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contra_payments', to='accounting.glsubaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('counterparty', 'Оплата контрагенту/клиенту'), ('opex', 'Прочий расход'), ('income', 'Прочий доход'), ('salary', 'Зарплата'), ('internal', 'Внутренний перевод')], db_index=True, default='counterparty', help_text='Бизнес-тип платежа: обычная оплата контрагенту или прочая операция (зарплата, коммуналка, штраф).', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='counterparty',
            field=models.ForeignKey(blank=True, help_text='Обязателен для kind=counterparty. Для opex/income/salary — опционален.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='counterparties.counterparty'),
        ),
    ]
