# Generated by Django 5.1.3 on 2026-04-24 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_expensearticle_journalentry_expense_article_and_more'),
        ('payments', '0002_add_contra_subaccount_and_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expense_article',
            field=models.ForeignKey(blank=True, help_text='Аналитическая статья (например «Газ», «Электричество»). При post_payment копируется в JournalEntry.expense_article.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.expensearticle'),
        ),
    ]
