# Generated by Django 5.1.3 on 2026-05-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_expense_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('counterparty', 'Оплата контрагенту/клиенту'), ('opex', 'Прочий расход'), ('income', 'Прочий доход'), ('salary', 'Зарплата'), ('internal', 'Внутренний перевод'), ('opening_balance_prepayment', 'Стартовая предоплата (миграция)')], db_index=True, default='counterparty', help_text='Бизнес-тип платежа: обычная оплата контрагенту или прочая операция (зарплата, коммуналка, штраф).', max_length=32),
        ),
    ]
