# Generated by Django 5.1.3 on 2026-05-12 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('message', models.TextField()),
                ('source', models.CharField(choices=[('otp', 'OTP-код'), ('notify', 'Уведомление'), ('manual', 'Ручная отправка')], db_index=True, default='notify', max_length=16)),
                ('purpose', models.CharField(blank=True, help_text="Контекст: 'login', 'sale_ready', 'debt_reminder' и т.п.", max_length=32)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено провайдеру'), ('delivered', 'Доставлено'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('provider_response', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True)),
                ('cost_uzs', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость по данным провайдера (price из status_by_id).', max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS-сообщение',
                'verbose_name_plural': 'SMS-сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='otp_smsmess_phone_6d849c_idx'), models.Index(fields=['status', '-created_at'], name='otp_smsmess_status_0f1595_idx'), models.Index(fields=['source', '-created_at'], name='otp_smsmess_source_c23914_idx')],
            },
        ),
    ]
