# Generated by Django 5.1.3 on 2026-04-24 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_batch_withdrawal_period_ends'),
        ('counterparties', '0002_initial'),
        ('currency', '0002_seed_cbu_beat'),
        ('feed', '0002_recipecomponent_vet_drug'),
        ('modules', '0005_alter_module_kind'),
        ('nomenclature', '0002_initial'),
        ('organizations', '0003_organizationmembership_work_phone_and_more'),
        ('vet', '0001_initial'),
        ('warehouses', '0003_alter_productionblock_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Проведён'), ('cancelled', 'Отменён')], default='draft', max_length=16)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('amount_foreign', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cost_uzs', models.DecimalField(decimal_places=2, default=0, help_text='Сумма себестоимости (для расчёта маржи).', max_digits=18)),
                ('paid_amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Частично оплачен'), ('paid', 'Оплачен'), ('overpaid', 'Переплата')], db_index=True, default='unpaid', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='currency.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='counterparties.counterparty')),
                ('exchange_rate_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_sales', to='currency.exchangerate')),
                ('module', models.ForeignKey(help_text='Source module: vet/slaughter/feedlot/...', on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='organizations.organization')),
                ('warehouse', models.ForeignKey(help_text='Откуда отгружаем (склад источника).', on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='warehouses.warehouse')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price_uzs', models.DecimalField(decimal_places=2, help_text='Ручная цена продажи за единицу (UZS).', max_digits=18)),
                ('cost_per_unit_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('line_total_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('line_cost_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='batches.batch')),
                ('feed_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='feed.feedbatch')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='nomenclature.nomenclatureitem')),
                ('vet_stock_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='vet.vetstockbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleorder')),
            ],
            options={
                'verbose_name': 'Строка продажи',
                'verbose_name_plural': 'Строки продажи',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['organization', '-date'], name='sales_saleo_organiz_3a4328_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['status'], name='sales_saleo_status_4180aa_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['customer'], name='sales_saleo_custome_739fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['payment_status'], name='sales_saleo_payment_e728a8_idx'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['module'], name='sales_saleo_module__5ddc7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saleorder',
            unique_together={('organization', 'doc_number')},
        ),
    ]
