# Generated by Django 5.1.3 on 2026-04-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleorder_exchange_rate_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Плановая дата оплаты (для отчёта дебиторского старения).', null=True),
        ),
    ]
