# Generated by Django 5.1.3 on 2026-05-04 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_business_logic_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCommunication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contacted_at', models.DateTimeField(db_index=True, help_text='Когда сотрудник связался с клиентом.')),
                ('method', models.CharField(choices=[('call', 'Звонок'), ('visit', 'Личная встреча'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'SMS'), ('email', 'Email'), ('other', 'Другое')], max_length=16)),
                ('outcome', models.CharField(choices=[('promised', 'Обещал оплатить'), ('refused', 'Отказался платить'), ('no_answer', 'Не ответил'), ('wrong_number', 'Неверный номер'), ('asked_defer', 'Попросил отсрочку'), ('other', 'Другое')], max_length=16)),
                ('customer_response', models.TextField(help_text='Что ответил клиент дословно — для CRM-истории и аудита.')),
                ('promised_pay_date', models.DateField(blank=True, db_index=True, help_text='Дата, к которой клиент обещал оплатить. Используется для follow-up напоминаний сотруднику если клиент не сдержал слово.', null=True)),
                ('next_action_date', models.DateField(blank=True, help_text='Когда сотруднику перезвонить (если no_answer / отсрочка).', null=True)),
                ('contacted_by', models.ForeignKey(help_text='Сотрудник, выполнивший касание.', on_delete=django.db.models.deletion.PROTECT, related_name='sale_communications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='sales.saleorder')),
            ],
            options={
                'verbose_name': 'Касание клиента',
                'verbose_name_plural': 'Касания клиента',
                'ordering': ['-contacted_at'],
                'indexes': [models.Index(fields=['order', '-contacted_at'], name='sales_salec_order_i_9d0aa2_idx'), models.Index(fields=['promised_pay_date'], name='sales_salec_promise_cc98b6_idx')],
            },
        ),
    ]
