# Generated by Django 5.1.3 on 2026-05-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salecommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecommunication',
            name='expected_pay_date',
            field=models.DateField(blank=True, db_index=True, help_text='Внутренний прогноз менеджера: когда оплата реально придёт. Может отличаться от promised_pay_date (например, клиент обещал пятницу, но менеджер по опыту знает что заплатит понедельник). Тоже триггерит задачу-напоминание после прохождения даты.', null=True),
        ),
        migrations.AddField(
            model_name='salecommunication',
            name='internal_note',
            field=models.TextField(blank=True, help_text='Заметка менеджера для внутреннего пользования (не попадает в TG/email клиенту). Например «скандалил», «жалуется на качество», «просил скидку 5%».'),
        ),
        migrations.AlterField(
            model_name='salecommunication',
            name='next_action_date',
            field=models.DateField(blank=True, db_index=True, help_text='Когда сотруднику перезвонить (если no_answer / отсрочка).', null=True),
        ),
        migrations.AlterField(
            model_name='salecommunication',
            name='promised_pay_date',
            field=models.DateField(blank=True, db_index=True, help_text='Что обещал САМ клиент (его слова). Используется для follow-up напоминаний если клиент не сдержал слово.', null=True),
        ),
    ]
