# Generated by Django 5.1.3 on 2026-05-04 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salecommunication_expected_pay_date_and_more'),
        ('vet', '0005_vetaccessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='vet_accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='vet.vetaccessory'),
        ),
    ]
