# Generated by Django 5.1.3 on 2026-05-04 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_feedbaglot_and_more'),
        ('sales', '0006_saleitem_vet_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='feed_bag_lot',
            field=models.ForeignKey(blank=True, help_text='Партия фасованного корма (мешки). При sale-confirm декрементится bags_remaining, quantity хранится в штуках мешков.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='feed.feedbaglot'),
        ),
    ]
