# Generated by Django 5.1.3 on 2026-05-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_saleitem_feed_bag_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='credit_override_reason',
            field=models.TextField(blank=True, help_text='Причина override кредитной блокировки. Заполняется при confirm_sale(force_credit_override=True). Без причины override невозможен.'),
        ),
    ]
