# Generated by Django 5.1.3 on 2026-05-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_seed_sales_module'),
        ('sales', '0008_saleorder_credit_override_reason'),
        ('warehouses', '0006_stockmovement_shrinkage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='kind',
            field=models.CharField(choices=[('regular', 'Обычная'), ('opening_balance', 'Стартовый долг (миграция)')], db_index=True, default='regular', help_text='Источник заказа. REGULAR — обычная продажа. OPENING_BALANCE — синтетический счёт миграции (без позиций / складов / выручки).', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Source module: vet/slaughter/feedlot/... NULL только для kind=opening_balance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='modules.module'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Откуда отгружаем (склад источника). NULL только для kind=opening_balance — у синтетического счёта склада нет.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='warehouses.warehouse'),
        ),
    ]
