# Generated by Django 5.1.3 on 2026-05-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_backfill_feed_bag_barcodes'),
        ('sales', '0010_materialize_opening_balance_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='raw_batch',
            field=models.ForeignKey(blank=True, help_text='Партия сырья комбикорма (зерно/премикс/жмых). Продаётся когда у фермера остатки и он хочет продать вместо переработки. При sale-confirm декрементится current_quantity (в кг), цена за ед. = закупочная (price_per_unit_uzs из приёмки).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='feed.rawmaterialbatch'),
        ),
    ]
