# Generated by Django 5.1.3 on 2026-04-23 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='work_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='work_status',
            field=models.CharField(choices=[('active', 'Активен'), ('vacation', 'Отпуск'), ('sick_leave', 'Больничный'), ('terminated', 'Уволен')], db_index=True, default='active', max_length=16),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'work_status'], name='organizatio_organiz_6d5cba_idx'),
        ),
    ]
