# Generated by Django 5.1.3 on 2026-05-12 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_default_org_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Руководитель этого сотрудника. На /people у юзера видны подчинённые (фильтр my_subordinates), на /payroll/balances он может быстро ставить +/− по их ЗП.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='organizations.organizationmembership'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['manager'], name='organizatio_manager_916276_idx'),
        ),
    ]
