# Generated by Django 5.1.3 on 2026-04-23 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_journalentry_batch_and_more'),
        ('batches', '0001_initial'),
        ('modules', '0003_seed_modules'),
        ('nomenclature', '0002_initial'),
        ('organizations', '0002_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterModuleTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=32)),
                ('transfer_date', models.DateTimeField(db_index=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cost_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('state', models.CharField(choices=[('draft', 'Черновик'), ('awaiting_acceptance', 'Ожидает приёма'), ('under_review', 'На проверке'), ('posted', 'Проведён'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=24)),
                ('review_reason', models.CharField(blank=True, max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inter_module_transfers', to='batches.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouses.productionblock')),
                ('from_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='modules.module')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouses.warehouse')),
                ('journal_receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('journal_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journalentry')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inter_module_transfers', to='nomenclature.nomenclatureitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inter_module_transfers', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stock_incoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouses.stockmovement')),
                ('stock_outgoing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouses.stockmovement')),
                ('to_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouses.productionblock')),
                ('to_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='modules.module')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouses.warehouse')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.unit')),
            ],
            options={
                'verbose_name': 'Межмодульная передача',
                'verbose_name_plural': 'Межмодульные передачи',
                'ordering': ['-transfer_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', '-transfer_date'], name='transfers_i_organiz_bda83e_idx'), models.Index(fields=['state'], name='transfers_i_state_36f345_idx'), models.Index(fields=['batch'], name='transfers_i_batch_i_36ca34_idx'), models.Index(fields=['to_module', 'state'], name='transfers_i_to_modu_53744f_idx'), models.Index(fields=['from_module', 'state'], name='transfers_i_from_mo_3ee908_idx')],
                'unique_together': {('organization', 'doc_number')},
            },
        ),
    ]
