# Generated by Django 5.1.3 on 2026-04-23 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_journalentry_batch_and_more'),
        ('batches', '0003_batch_withdrawal_period_ends'),
        ('feed', '0001_initial'),
        ('modules', '0003_seed_modules'),
        ('nomenclature', '0002_initial'),
        ('organizations', '0002_initial'),
        ('transfers', '0001_initial'),
        ('warehouses', '0003_alter_productionblock_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intermoduletransfer',
            name='feed_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inter_module_transfers', to='feed.feedbatch'),
        ),
        migrations.AlterField(
            model_name='intermoduletransfer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inter_module_transfers', to='batches.batch'),
        ),
        migrations.AddIndex(
            model_name='intermoduletransfer',
            index=models.Index(fields=['feed_batch'], name='transfers_i_feed_ba_b5090c_idx'),
        ),
    ]
