name: Deploy Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/_test.yml

  deploy:
    needs: tests
    uses: ./.github/workflows/_deploy.yml
    with:
      environment_name: staging
      deploy_path: /opt/yembro/staging
      image_alias: staging
      frontend_api_base_url: ''
      public_base_url: https://staging.erp.yembro.uz
    secrets: inherit
