name: Deploy Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment_name: production
      deploy_path: /opt/yembro/prod
      image_alias: production
    secrets: inherit
