name: Deploy Production

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/_test.yml

  deploy:
    needs: tests
    uses: ./.github/workflows/_deploy.yml
    with:
      environment_name: production
      deploy_path: /opt/yembro/prod
      image_alias: production
      frontend_api_base_url: /api
      public_base_url: https://erp.yembro.uz
    secrets: inherit
