# Generated by Django 5.1.3 on 2026-04-23 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomponent',
            name='vet_drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feed_recipe_components', to='vet.vetdrug'),
        ),
    ]
