# Generated by Django 5.1.3 on 2026-04-25 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_initial'),
        ('feed', '0002_recipecomponent_vet_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='dockage_pct_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сорность %.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='gross_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Физический вес на весах при приёмке.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='moisture_pct_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Фактическая влажность сырья (%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='moisture_pct_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Базисная влажность (snapshot из nomenclature на момент приёмки).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='settlement_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Зачётный вес после поправки на влажность/сорность (== quantity).', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='shrinkage_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Итоговая поправка % (Дюваль + сорность).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='storage_bin',
            field=models.CharField(blank=True, help_text='Бункер/секция склада (плоская строка, например «БК-3»).', max_length=64),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_batches', to='counterparties.counterparty'),
        ),
    ]
