# Generated by Django 5.1.3 on 2026-05-04 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_seed_feed_shrinkage_beat'),
        ('modules', '0006_seed_sales_module'),
        ('organizations', '0004_rename_default_org_name'),
        ('warehouses', '0006_stockmovement_shrinkage_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBagLot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_index=True, max_length=64)),
                ('bag_weight_kg', models.DecimalField(decimal_places=3, help_text='Вес одного мешка в кг (типично 50.000).', max_digits=8)),
                ('bags_initial', models.PositiveIntegerField(help_text='Сколько мешков расфасовано при создании партии.')),
                ('bags_remaining', models.PositiveIntegerField(help_text='Текущий остаток в мешках (декрементируется при продаже).')),
                ('unit_cost_uzs', models.DecimalField(decimal_places=2, help_text='Себестоимость одного мешка (UZS).', max_digits=18)),
                ('total_cost_uzs', models.DecimalField(decimal_places=2, help_text='Итого стоимость партии = bags_initial × unit_cost.', max_digits=18)),
                ('packaged_at', models.DateTimeField(db_index=True)),
                ('is_medicated', models.BooleanField(default=False)),
                ('withdrawal_period_days', models.PositiveSmallIntegerField(default=0)),
                ('withdrawal_period_ends', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('active', 'В наличии'), ('depleted', 'Исчерпана'), ('recalled', 'Отозвана')], db_index=True, default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Партия фасованного корма',
                'verbose_name_plural': 'Партии фасованного корма',
                'ordering': ['-packaged_at', 'doc_number'],
            },
        ),
        migrations.RenameIndex(
            model_name='feedlotshrinkagestate',
            new_name='feed_feedlo_organiz_c68e32_idx',
            old_name='feed_feedlo_organiz_91d12c_idx',
        ),
        migrations.RenameIndex(
            model_name='feedlotshrinkagestate',
            new_name='feed_feedlo_profile_fdf2ef_idx',
            old_name='feed_feedlo_profile_3e2da4_idx',
        ),
        migrations.RenameIndex(
            model_name='feedshrinkageprofile',
            new_name='feed_feedsh_organiz_800e3d_idx',
            old_name='feed_feedsh_organiz_d4afa9_idx',
        ),
        migrations.RenameIndex(
            model_name='feedshrinkageprofile',
            new_name='feed_feedsh_nomencl_e777e7_idx',
            old_name='feed_feedsh_nomencl_3a0d76_idx',
        ),
        migrations.RenameIndex(
            model_name='feedshrinkageprofile',
            new_name='feed_feedsh_recipe__ac305d_idx',
            old_name='feed_feedsh_recipe__c30b22_idx',
        ),
        migrations.AddField(
            model_name='feedbaglot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbaglot',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_bag_lots', to='modules.module'),
        ),
        migrations.AddField(
            model_name='feedbaglot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_bag_lots', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='feedbaglot',
            name='recipe_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bag_lots', to='feed.recipeversion'),
        ),
        migrations.AddField(
            model_name='feedbaglot',
            name='source_feed_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bag_lots', to='feed.feedbatch'),
        ),
        migrations.AddField(
            model_name='feedbaglot',
            name='storage_bin',
            field=models.ForeignKey(blank=True, help_text='Опциональный бункер/зона хранения внутри склада.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stored_feed_bag_lots', to='warehouses.productionblock'),
        ),
        migrations.AddField(
            model_name='feedbaglot',
            name='storage_warehouse',
            field=models.ForeignKey(help_text='Склад мешков (отдельный от склада замесов).', on_delete=django.db.models.deletion.PROTECT, related_name='feed_bag_lots', to='warehouses.warehouse'),
        ),
        migrations.AddIndex(
            model_name='feedbaglot',
            index=models.Index(fields=['organization', 'status'], name='feed_feedba_organiz_3a3ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbaglot',
            index=models.Index(fields=['source_feed_batch', 'status'], name='feed_feedba_source__aa042b_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbaglot',
            index=models.Index(fields=['recipe_version', 'status'], name='feed_feedba_recipe__524b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbaglot',
            index=models.Index(fields=['storage_warehouse', 'status'], name='feed_feedba_storage_e46e33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbaglot',
            unique_together={('organization', 'doc_number')},
        ),
    ]
