# Generated by Django 5.1.3 on 2026-05-06 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_feedbaglot_and_more'),
        ('modules', '0006_seed_sales_module'),
        ('organizations', '0004_rename_default_org_name'),
        ('warehouses', '0006_stockmovement_shrinkage_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbaglot',
            unique_together={('organization', 'doc_number')},
        ),
        migrations.AddField(
            model_name='feedbaglot',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Штрих-код партии мешков для розничной продажи и сканирования. Авто-генерируется при создании в формате FEED-{recipe}-{rand4}. Сканирование открывает /scan/<barcode> с инфой о партии.', max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='feedbaglot',
            unique_together={('organization', 'barcode'), ('organization', 'doc_number')},
        ),
        migrations.AddIndex(
            model_name='feedbaglot',
            index=models.Index(fields=['organization', 'barcode'], name='feed_feedba_organiz_2d499f_idx'),
        ),
    ]
